name: CI
on:
    # Enables running the workflow manually from the Actions tab
    workflow_dispatch:

    push:
        branches:
            - main
        tags:
            - v*

    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        permissions:
          contents: read

        steps:
            - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
              with:
                  persist-credentials: false

            - name: Setup Deno
              uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
              with:
                deno-version: v2.x

            - name: Check Formatting
              run: deno task fmt

            - name: Check Linting
              run: deno task lint

            - name: Build
              run: deno task build

            - name: Install Go
              uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
              with:
                  go-version: 1.26.x
                  cache: false

            - name: Install k6
              run: go install go.k6.io/k6@latest

            - name: Build the docker-compose stack
              uses: hoverkraft-tech/compose-action@b659c744ee9bed25aea2307c017ad849bd104433 # v3.2.0
              with:
                  up-flags: '-d'
                  down-flags: '-v'

            - name: Wait for the localstack scripts to have been applied
              run: sleep 30

            - name: Test
              run: deno task test:ci
