name: "Auto assign maintainer to issue"
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  assign-maintainer:
    uses: grafana/k6/.github/workflows/issue-auto-assign.yml@1646ca06eeb44c5e495426f1226c9a4bc241d741 # master